name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Invalid
        if: github.event.label.name == 'invalid'
        uses: actions-cool/issues-helper@e2ff99831a4f13625d35064e2b3dfe65c07a0396 # v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, to help us communicate and handle issues more efficiently, we ask that issues be submitted following a specific format. Your issue did not meet the requirements and has been automatically closed. Please create a new issue following the templateâ€”we look forward to your feedback!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä¸ºäº†èƒ½å¤Ÿæ›´é«˜æ•ˆåœ°æ²Ÿé€šå’Œå¤„ç†é—®é¢˜ï¼Œæˆ‘ä»¬å¸Œæœ› issue æŒ‰ä¸€å®šæ ¼å¼æäº¤ã€‚ä½ çš„ issue å› ä¸ºä¸ç¬¦åˆè¦æ±‚è€Œè¢«è‡ªåŠ¨å…³é—­ã€‚è¯·æŒ‰ç…§æ¨¡æ¿é‡æ–°åˆ›å»º issueï¼Œæˆ‘ä»¬å¾ˆæœŸå¾…ä½ çš„åé¦ˆï¼

      - name: Need More Info
        if: github.event.label.name == 'need more info'
        uses: actions-cool/issues-helper@e2ff99831a4f13625d35064e2b3dfe65c07a0396 # v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, to help others understand and resolve your issue more quickly, please provide some additional details or context information.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä¸ºäº†å¸®åŠ©æŸ¥çœ‹æ­¤ issue çš„äººæ›´å¿«åœ°ç†è§£å’Œå¤„ç†ä½ çš„é—®é¢˜ï¼Œè¯·æä¾›ä¸€äº›æ›´å¤šç»†èŠ‚æˆ–ä¸Šä¸‹æ–‡ä¿¡æ¯ã€‚

      - name: PR Welcome
        if: github.event.label.name == 'ğŸ©µ PR Welcome'
        uses: actions-cool/issues-helper@e2ff99831a4f13625d35064e2b3dfe65c07a0396 # v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}! We agree with this issue and warmly welcome PRs!
            Anyone interested in helping solve this issue is encouraged to contribute!
            If you want to claim it, please reply under this issue to avoid duplicate submissions. See the contribution guide for details.

            å—¨ @${{ github.event.issue.user.login}}ï¼æ„Ÿè°¢ä½ çš„åé¦ˆï¼Œæˆ‘ä»¬å¾ˆè®¤åŒè¿™ä¸ªé—®é¢˜ï¼Œä¹Ÿéå¸¸æ¬¢è¿æäº¤ PR !
            æ¬¢è¿ä»»ä½•æœ‰å…´è¶£çš„å¼€å‘è€…å‚ä¸è§£å†³æ­¤é—®é¢˜ï¼ŒæœŸå¾…ä½ çš„è´¡çŒ®ï¼
            å¦‚æƒ³è®¤é¢†ï¼Œè¯·åœ¨æ­¤ issue ä¸‹å‘ŠçŸ¥ä»¥é¿å…å¤šäººé‡å¤æäº¤ï¼Œè¯¦æƒ…è¯·å‚è€ƒè´¡çŒ®æŒ‡å—ã€‚
